"""initial videre schema

Revision ID: f902a47f1533
Revises: 
Create Date: 2026-07-24 17:54:58.098349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f902a47f1533'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS videre")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clusters')),
    schema='videre'
    )
    op.create_table('failure_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('root_cause_tag', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('triggered_by_id', sa.String(length=64), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('node_not_ready', 'gpu', 'job', 'capacity')", name=op.f('ck_failure_records_category_valid')),
    sa.CheckConstraint("entity_type IN ('node', 'gpu', 'job')", name=op.f('ck_failure_records_entity_type_valid')),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['videre.failure_records.id'], name=op.f('fk_failure_records_triggered_by_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failure_records')),
    sa.UniqueConstraint('event_id', name=op.f('uq_failure_records_event_id')),
    schema='videre'
    )
    op.create_index('ix_failure_records_correlation_id', 'failure_records', ['correlation_id'], unique=False, schema='videre')
    op.create_index('ix_failure_records_detected_at', 'failure_records', ['detected_at'], unique=False, schema='videre')
    op.create_index('ix_failure_records_entity_type_entity_id', 'failure_records', ['entity_type', 'entity_id'], unique=False, schema='videre')
    op.create_index('ix_failure_records_unresolved', 'failure_records', ['entity_type', 'entity_id'], unique=False, schema='videre', postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_table('jobs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('requested_cpu_cores', sa.Integer(), nullable=False),
    sa.Column('requested_memory_gb', sa.Integer(), nullable=False),
    sa.Column('requested_gpu_count', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pod_name', sa.String(length=253), nullable=True),
    sa.Column('last_checkpoint_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkpoint_corrupt', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("lifecycle_state IN ('PENDING', 'RUNNING', 'FAILED', 'COMPLETED')", name=op.f('ck_jobs_lifecycle_state_valid')),
    sa.ForeignKeyConstraint(['cluster_id'], ['videre.clusters.id'], name=op.f('fk_jobs_cluster_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    schema='videre'
    )
    op.create_index(op.f('ix_jobs_cluster_id'), 'jobs', ['cluster_id'], unique=False, schema='videre')
    op.create_index('ix_jobs_completed_at', 'jobs', ['completed_at'], unique=False, schema='videre')
    op.create_index('ix_jobs_lifecycle_state', 'jobs', ['lifecycle_state'], unique=False, schema='videre')
    op.create_table('nodes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('memory_gb', sa.Integer(), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('health_state', sa.String(length=32), nullable=False),
    sa.Column('simulated_node_label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("health_state IN ('READY', 'NOT_READY', 'DRAINING', 'CORDONED')", name=op.f('ck_nodes_health_state_valid')),
    sa.ForeignKeyConstraint(['cluster_id'], ['videre.clusters.id'], name=op.f('fk_nodes_cluster_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes')),
    schema='videre'
    )
    op.create_index(op.f('ix_nodes_cluster_id'), 'nodes', ['cluster_id'], unique=False, schema='videre')
    op.create_index('ix_nodes_health_state', 'nodes', ['health_state'], unique=False, schema='videre')
    op.create_table('gpus',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('utilization_percentage', sa.Float(), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=False),
    sa.Column('memory_used_mb', sa.Integer(), nullable=False),
    sa.Column('memory_total_mb', sa.Integer(), nullable=False),
    sa.Column('ecc_correctable_count', sa.Integer(), nullable=False),
    sa.Column('ecc_uncorrectable_count', sa.Integer(), nullable=False),
    sa.Column('xid_error_count', sa.Integer(), nullable=False),
    sa.Column('health_state', sa.String(length=32), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("health_state IN ('HEALTHY', 'THROTTLING', 'DEGRADED', 'FAILED')", name=op.f('ck_gpus_health_state_valid')),
    sa.ForeignKeyConstraint(['node_id'], ['videre.nodes.id'], name=op.f('fk_gpus_node_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gpus')),
    schema='videre'
    )
    op.create_index('ix_gpus_health_state', 'gpus', ['health_state'], unique=False, schema='videre')
    op.create_index(op.f('ix_gpus_node_id'), 'gpus', ['node_id'], unique=False, schema='videre')
    op.create_table('job_node_assignments',
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['videre.jobs.id'], name=op.f('fk_job_node_assignments_job_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['videre.nodes.id'], name=op.f('fk_job_node_assignments_node_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'node_id', name=op.f('pk_job_node_assignments')),
    schema='videre'
    )
    op.create_index(op.f('ix_job_node_assignments_node_id'), 'job_node_assignments', ['node_id'], unique=False, schema='videre')
    op.create_table('scheduler_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('related_job_id', sa.String(length=128), nullable=True),
    sa.Column('related_node_id', sa.String(length=64), nullable=True),
    sa.Column('delay_seconds', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.CheckConstraint("(type = 'QUEUEING_DELAY') = (delay_seconds IS NOT NULL)", name=op.f('ck_scheduler_events_delay_matches_type')),
    sa.CheckConstraint("type IN ('PLACEMENT', 'PREEMPTION', 'QUEUEING_DELAY')", name=op.f('ck_scheduler_events_type_valid')),
    sa.ForeignKeyConstraint(['related_job_id'], ['videre.jobs.id'], name=op.f('fk_scheduler_events_related_job_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_node_id'], ['videre.nodes.id'], name=op.f('fk_scheduler_events_related_node_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduler_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_scheduler_events_event_id')),
    schema='videre'
    )
    op.create_index(op.f('ix_scheduler_events_related_job_id'), 'scheduler_events', ['related_job_id'], unique=False, schema='videre')
    op.create_index(op.f('ix_scheduler_events_related_node_id'), 'scheduler_events', ['related_node_id'], unique=False, schema='videre')
    op.create_index('ix_scheduler_events_timestamp', 'scheduler_events', ['timestamp'], unique=False, schema='videre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduler_events_timestamp', table_name='scheduler_events', schema='videre')
    op.drop_index(op.f('ix_scheduler_events_related_node_id'), table_name='scheduler_events', schema='videre')
    op.drop_index(op.f('ix_scheduler_events_related_job_id'), table_name='scheduler_events', schema='videre')
    op.drop_table('scheduler_events', schema='videre')
    op.drop_index(op.f('ix_job_node_assignments_node_id'), table_name='job_node_assignments', schema='videre')
    op.drop_table('job_node_assignments', schema='videre')
    op.drop_index(op.f('ix_gpus_node_id'), table_name='gpus', schema='videre')
    op.drop_index('ix_gpus_health_state', table_name='gpus', schema='videre')
    op.drop_table('gpus', schema='videre')
    op.drop_index('ix_nodes_health_state', table_name='nodes', schema='videre')
    op.drop_index(op.f('ix_nodes_cluster_id'), table_name='nodes', schema='videre')
    op.drop_table('nodes', schema='videre')
    op.drop_index('ix_jobs_lifecycle_state', table_name='jobs', schema='videre')
    op.drop_index('ix_jobs_completed_at', table_name='jobs', schema='videre')
    op.drop_index(op.f('ix_jobs_cluster_id'), table_name='jobs', schema='videre')
    op.drop_table('jobs', schema='videre')
    op.drop_index('ix_failure_records_unresolved', table_name='failure_records', schema='videre', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index('ix_failure_records_entity_type_entity_id', table_name='failure_records', schema='videre')
    op.drop_index('ix_failure_records_detected_at', table_name='failure_records', schema='videre')
    op.drop_index('ix_failure_records_correlation_id', table_name='failure_records', schema='videre')
    op.drop_table('failure_records', schema='videre')
    op.drop_table('clusters', schema='videre')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS videre CASCADE")
