"""
Materialize simulated running jobs as real, lightweight Kubernetes Jobs on the single node.
Each real pod is a stand-in, annotated back to its simulated node, running an outcome
state machine producing the real result: exit 0 for completed, OOMKilled for a memory bomb, or exit 1 for error.
"""

from __future__ import annotations

import logging
import time

from kubernetes import client, config
from kubernetes.stream import stream

from videre.models import Job

logger = logging.getLogger("videre.simulator.materializer")

# wait for the /tmp/outcome file to appear, then read its content and exit with the appropriate code
_OUTCOME_SCRIPT = (
    "until [ -f /tmp/outcome ]; do sleep 1; done; "
    'case "$(cat /tmp/outcome)" in '
    "complete) exit 0 ;; "
    "oom) dd if=/dev/zero of=/dev/null bs=512M ;; "
    "*) exit 1 ;; "
    "esac"
)

MATERIALIZED_LABEL = "videre.io/materialized"
SIMULATED_JOB_LABEL = "videre.io/simulated-job"
SIMULATED_NODE_LABEL = "videre.io/simulated-node"


def build_materialized_job(
    job: Job,
    node_id: str,
    *,
    image: str = "busybox:1.37",
    ttl_seconds_after_finished: int = 300,
    active_deadline_seconds: int = 120,
) -> client.V1Job:
    # labels attached to the pod and job for later identification
    labels = {
        "app.kubernetes.io/part-of": "videre",
        MATERIALIZED_LABEL: "true",
        SIMULATED_JOB_LABEL: job.id,
        SIMULATED_NODE_LABEL: node_id,
    }
    
    # define the container that will run the outcome script, with microscopic resources
    container = client.V1Container(
        name="workload",
        image=image,
        command=["sh", "-c", _OUTCOME_SCRIPT],
        resources=client.V1ResourceRequirements(
            requests={"cpu": "5m", "memory": "16Mi"},
            limits={"cpu": "50m", "memory": "32Mi"},
        )
    )
    
    # define the wrapper around the container to define Pod-level behavior
    pod_spec = client.V1PodSpec(restart_policy="Never", containers=[container])    # simulated jobs are one-shot
    template = client.V1PodTemplateSpec(metadata=client.V1ObjectMeta(labels=labels), spec=pod_spec)
    
    # define the Job spec that wraps the pod template and controls job-level behavior
    job_spec = client.V1JobSpec(
        template=template,
        backoff_limit=0,
        ttl_seconds_after_finished=ttl_seconds_after_finished,
        active_deadline_seconds=active_deadline_seconds,
    )
    
    # top-level Job object passed to the Kubernetes API to create the job
    return client.V1Job(
        metadata=client.V1ObjectMeta(name=f"sim-{job.id}", labels=labels),
        spec=job_spec
    )


class KubernetesJobMaterializer:
    def __init__(self, *, namespace: str = "videre", ttl_seconds_after_finished: int = 300) -> None:
        # authenticate a Kubernetes client, either from within a cluster or from a kubeconfig file
        try:
            config.load_incluster_config()
        except config.ConfigException:
            config.load_kube_config()
        
        self._namespace = namespace
        self._batch = client.BatchV1Api()   # responsible for task-oriented workloads (e.g., creating Jobs)
        self._core = client.CoreV1Api()     # responsible for managing core resources (e.g., Pods)
        self._ttl_seconds_after_finished = ttl_seconds_after_finished
    
    def materialize(self, job: Job, node_id: str) -> str:
        self._batch.create_namespaced_job(
            self._namespace,
            build_materialized_job(job, node_id, ttl_seconds_after_finished=self._ttl_seconds_after_finished)
        )
        return self._wait_for_pod_name(job.id)    # return the pod name uniquely generated by Kubernetes
    
    def signal_outcome(self, pod_name: str, outcome: str) -> None:
        try:    # open a WebSocket connection to the API server and write the outcome to /tmp/outcome in the pod
            stream(
                self._core.connect_get_namespaced_pod_exec,
                pod_name,
                self._namespace,
                command=["sh", "-c", f"echo {outcome} > /tmp/outcome"],
                stderr=True,
                stdout=True,
                stdin=False,
                tty=False,
            )
        except Exception as error:
            logger.warning("outcome signal failed", extra={"pod": pod_name, "error": str(error)})
    
    def _wait_for_pod_name(self, job_id: str, *, timeout_seconds: float = 15.0) -> str:
        deadline = time.monotonic() + timeout_seconds
        selector = f"{SIMULATED_JOB_LABEL}={job_id}"
        while time.monotonic() < deadline:
            pods = self._core.list_namespaced_pod(self._namespace, label_selector=selector)
            if pods.items:
                return str(pods.items[0].metadata.name)
            time.sleep(0.5)
        raise TimeoutError(f"pod for materialized job {job_id} did not appear within {timeout_seconds}s")
